name: Deploy JavaDoc

on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
      project_description:
        required: true
        type: string
      custom_domain:
        required: true
        type: string
      javadocs_branch:
        description: 'Branch containing JavaDocs'
        required: false
        type: string
        default: 'javadocs'
    secrets:
      CLOUDFLARE_ACCOUNT_ID:
        description: 'Cloudflare Account Id for deployment'
        required: true
      CLOUDFLARE_API_TOKEN:
        description: 'Cloudflare API Token for deployment'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout template repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: Siroshun09/javadoc-page-template
          path: template

      - name: Checkout javadocs branch
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: ${{ github.repository }}
          ref: ${{ inputs.javadocs_branch }}
          path: javadocs

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: 'template/.node-version'

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          package_json_file: 'template/package.json'

      - name: Install dependencies
        working-directory: template
        run: pnpm install

      - name: Run setup-javadoc
        working-directory: template
        run: pnpm setup-javadoc
        env:
          VITE_WORKING_DIR: work
          VITE_JAVADOC_DIR: ../javadocs
          VITE_PROJECT_NAME: ${{ inputs.project_name }}
          VITE_PROJECT_DESCRIPTION: ${{ inputs.project_description }}
          VITE_PROJECT_GITHUB: https://github.com/${{ github.repository }}

      - name: Run setup-wrangler
        working-directory: template
        run: pnpm setup-wrangler
        env:
          VITE_PROJECT_NAME: ${{ inputs.project_name }}
          VITE_CUSTOM_DOMAIN: ${{ inputs.custom_domain }}

      - name: Generate pages
        working-directory: template
        run: pnpm build
        env:
          VITE_WORKING_DIR: work

      - name: Deploy to Cloudflare
        working-directory: template
        run: pnpm wrangler deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
